# --- Build Stage ---
FROM python:3.9-slim-bullseye AS builder
LABEL stage="fakesnow-builder"

WORKDIR /app_build

ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt && \
    echo "--- requirements.txt installation complete ---"

# --- Runtime Stage ---
FROM python:3.9-slim-bullseye AS runtime
LABEL stage="fakesnow-runtime"

WORKDIR /fakesnow_app

COPY --from=builder /opt/venv /opt/venv

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY wrapper.py /fakesnow_app/wrapper.py

EXPOSE 8080

ENV FAKESNOW_HOST="0.0.0.0"

ENV FAKESNOW_PORT="8080"

CMD ["/opt/venv/bin/python", "/fakesnow_app/wrapper.py"]